Rdf Parser
AndersSpringborg/knox-d pull request #18
Opened 2020-12-04 11:25 UTC by madsthom

2020-12-04 14:20 UTC, kaareHH requested changes

2020-12-04 14:20 UTC, kaareHH commented on knowledge_graph/knowledgegraph.py
> +
Hvis relation og subject ikke findes i vores ontology skal triplen ikke konstrueres med "literaltype.string" da hverken rel eller subj må laves som en literaltype. Alt i "else" skal slettes, og så skal der fixes lidt om på if'erne :D

2020-12-14 12:10 UTC, AndersSpringborg commented
Sry, det var ikke meningen

2020-12-14 13:15 UTC, AndersSpringborg approved these changes
LGTM!!! (looks good to me || legit trash module)

2020-12-14 13:17 UTC, kaareHH approved these changes
Legit garbage trash module

2020-12-14 13:17 UTC, merged