Implemented pipeline. Connected the components
AndersSpringborg/knox-d pull request #7
Opened 2020-11-05 15:00 UTC by kaareHH

The pipeline has been implemented, and can be run with the "mi_graph.py" file. 
Some of the components have been changed, in order to be connected with each other. 
Tests have been updated.

If you want to try and run the pipeline, please use the file in "examples/grundfos_test.json"

2020-11-12 08:26 UTC, mkakbas approved these changes

2020-11-12 08:35 UTC, KasperSWinkler submitted a review, later dismissed

2020-11-16 12:33 UTC, AndersSpringborg requested changes

2020-11-16 12:33 UTC, AndersSpringborg commented on preprocess/cleaner_imp.py
> +
there's no test on dis ting

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        token = tokens[0].pop()
```suggestion
        first_sentance = self.model.tokens()[0]
        token =  first_sentance.pop()
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        token = tokens[0].pop()
```suggestion
        first_sentance= self.model.tokens()[0]
        token = first_sentance.pop()
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_argsparser.py
> +
```suggestion
```

delete lines

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        token = tokens[0].pop()
```suggestion
        first_sentance= self.model.tokens()[0]
        token = first_sentance.pop()
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        token = tokens[0].pop()
```suggestion
        first_sentance= self.model.tokens()[0]
        token = first_sentance.pop()
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        token = tokens[0].pop()
```suggestion
        first_sentance= self.model.tokens()[0]
        token = first_sentance.pop()
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        apple = tokens[0][0]
```suggestion
        first_sentance= self.model.tokens()[0]
        apple= first_sentance[0]
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        _is = tokens[0][1]
```suggestion
        first_sentance= self.model.tokens()[0]
        _is = first_sentance[1]
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        looking = tokens[0][2]
```suggestion
        first_sentance= self.model.tokens()[0]
        looking = first_sentance[2]
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        at = tokens[0][3]
```suggestion
        first_sentance= self.model.tokens()[0]
        at = first_sentance[3]
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        buying = tokens[0][4]
```suggestion
        first_sentance= self.model.tokens()[0]
        buying = first_sentance[4]
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        UK = tokens[0][5]
```suggestion
        first_sentance= self.model.tokens()[0]
        UK = first_sentance[5]
```

2020-11-16 12:33 UTC, AndersSpringborg commented on tests/test_model.py
> +        startup = tokens[0][6]
```suggestion
        first_sentance= self.model.tokens()[0]
        startup = first_sentance[6]
```

2020-11-16 12:40 UTC, AndersSpringborg approved these changes
Very nice

2020-11-16 12:41 UTC, mkakbas approved these changes

2020-11-16 12:46 UTC, merged